name: higlass-scipy19
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.7
  - nodejs=10.*
  - pip
  - pip:
    - jupyterlab==1.1.1
    - ipywidgets==7.5.1
    - higlass-python==0.4.1
    - nbserverproxy
